# Generated by Django 3.2.9 on 2021-11-15 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alloriginalurl',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='allshorturl',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
