# Generated by Django 3.2.9 on 2021-11-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shorturl_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allshorturl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shorturl'),
        ),
    ]
