# Generated by Django 3.2.9 on 2021-11-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211117_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='original_url',
            new_name='originalURL',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_url',
            new_name='shortURL',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='url_hash',
            new_name='urlHash',
        ),
    ]
