# Generated by Django 3.2.9 on 2021-11-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_originalurl_shorturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalurl',
            name='shorten_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
