# Generated by Django 3.2.9 on 2021-11-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211117_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllOriginalURL',
        ),
        migrations.DeleteModel(
            name='AllShortURL',
        ),
    ]
