# Generated by Django 3.2.9 on 2021-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211117_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalurl',
            name='shortened',
            field=models.IntegerField(default=0),
        ),
    ]
