# Generated by Django 3.2.9 on 2021-11-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_originalurl_shortened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalurl',
            name='shortened',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
