# Generated by Django 3.2.9 on 2021-11-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_originalurl_urlhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalurl',
            name='shortURL',
            field=models.URLField(default='', max_length=2048),
        ),
    ]
