# Generated by Django 3.2.9 on 2021-11-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_originalurl_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalurl',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
